name: drones
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bullet-cpp=3.25
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - icc_rt=2022.1.0
  - libffi=3.4.4
  - libhwloc=2.12.1
  - libiconv=1.18
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - mkl=2025.3.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openssl=3.6.0
  - pip=25.3
  - pybullet=3.25
  - python=3.10.19
  - python_abi=3.10
  - scipy=1.15.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - cffi==2.0.0
      - clarabel==0.11.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - contourpy==1.3.2
      - control==0.10.2
      - cvxpy==1.7.4
      - cycler==0.12.1
      - exceptiongroup==1.3.1
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - gym-pybullet-drones==2.0.0
      - gymnasium==1.2.2
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.4.2
      - osqp==1.0.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pluggy==1.6.0
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==9.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scs==3.2.9
      - six==1.17.0
      - stable-baselines3==2.7.0
      - sympy==1.14.0
      - tomli==2.3.0
      - torch==2.9.1
      - transforms3d==0.4.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
prefix: C:\Users\samle\anaconda3\envs\drones
