name: PDM_EMBER_ENV
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pybullet
  - matplotlib
  - pandas
  - cvxpy
  - osqp
  - scs
  - control
  - pytest

  - pip:
      - git+https://github.com/utiasDSL/gym-pybullet-drones.git@main
      - gymnasium
      - stable-baselines3
      - torch
      - transforms3d
